# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yue Hong | æ´ªç¥
title: Power Market Algorithm Engineer, Passionate about Data Science
email: 18916838915@163.com
website: https://emmonade.github.io/homepage/
location: Beijing, China

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  emmonade
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: æ´ªç¥
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Yue Hong and you can call me Luna in English, and I'm currently an algorithm engineer. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Statistics</mark>ã€<mark>Python</mark> and <mark>Eating Delicious Food</mark>

  If you are interested, this is my official cv ğŸ‘‰ 

content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Peking University
        caption: 2021 - 2023
        sub_title: MSc Applied Statistics
        quote: >
          Established in 1898, Peking University is the oldest higher education institution in China, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in modern China.
        description: | # this will include new lines to allow paragraphs
          ğŸ“ **Major Courses**: Machine Learning, Neural Networks and Deep Learning, Deep Learning and Reinforcement Learning, Advanced Multivariate Statistics, Statistical Learning, Data Visualization, Statistical Inference, Big Data Case Study and Practice, Risk Management and Financial Institutions, Big Data Distributed Computing and Storage
         
          ğŸš© **GPA**: 3.5 / 4.0
          
          ğŸ–ï¸ **Honors & Awards**: Second Prize Scholarship of the Masterâ€™s Program, School of Mathematical Sciences, Peking University
        
          <a href="lib/thesis_Msc.pdf" target="_blank">Click here to view my masterâ€™s thesis.</a>
          
      - layout: left
        title:  East China Normal University
        caption: 2016 - 2020
        sub_title: BSc Statistics
        quote: >
          ECNU is a public research university located in Shanghai, China. Established in 1951 through the merger of Daxia University and Guanghua University, it is the first normal university founded by the Peopleâ€™s Republic of China.
        description: | # this will include new lines to allow paragraphs
          ğŸ“ **Major Courses**: Advanced Algebra, Mathematical Analysis, Stochastic Processes, Multivariate Statistical Analysis, Time Series Analysis, Quality Management, Design of Experiments, Sampling Survey; Probability Theory, Mathematical Statistics; Macroeconomics, Microeconomics, Monetary Finance, Principles of Accounting, Corporate Finance, etc.
        
          <a href="lib/thesis_Bsc.pdf" target="_blank">Click here to view my undergraduate thesis.</a>

# experience
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: QCTC
        link: qctc.com.cn
        # link_text: boringcompany.com
        sub_title: Algorithm Engineer
        caption: current job
        description: | # this will include new lines to allow paragraphs
            I am currently an algorithm enginneer at this company,mainly responsible for designing algorithms related to:
            - electricity load forecasting
            - renewable energy output forecasting
            - electricity price forecasting across various provinces

      - layout: left
        title: Beijing Institute of Big Data Research
        sub_title: BIBDR
        link: bibdr.org
        # link_text: boringcompany.com
        sub_title: Data Analysis
        caption: internshipï¼Œ2022.12~2023.5
        description: | # this will include new lines to allow paragraphs
            Participated in a data science project focused on rating technology-based enterprises, where I developed end-to-end modeling and data analysis skills.
      
      - layout: left
        title: China Satellite Network Group Co., Ltd
        # link_text: boringcompany.com
        sub_title: Algorithm Engineer
        caption: internshipï¼Œ2022.01~2022.6
        description: | # this will include new lines to allow paragraphs
            During this internship, I was exposed to some cutting-edge algorithms and their applications in task scheduling scenarios for large-scale constellations. I am grateful for this internship, as it ignited my passion for technology and algorithms as a career path.
            

# projects
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: Undergraduate Thesis 
        caption: rate risk,complex network, time analysis
        description: |
          Research on Exchange Rate Risk in Export Credit Insurance under the Background of â€œOne Belt, One Roadâ€ using Complex Network

          <a href="lib/thesis_Msc.pdf" target="_blank">Click here to view the thesis.</a>
      
      - layout: right
        title: Master's Thesis
        caption: machine learning, corporate evaluation
        description: |
          Research on the Promotion Mechanism of High-tech Product Revenue for Technology-oriented SMEs with a XGBoost Algorithm for Feature Importance Evaluation
          
          <a href="lib/thesis_Msc.pdf" target="_blank">Click here to view the thesis.</a>

          
      
      - layout: right
        title: Data Visualization Project 
        sub_title: Visualization of teachers in the disciplines of History and Archaeology at Chinese universities.
        description: |
          By using data on university teachersâ€™ alma maters, graduation times, and current institutions as input, the visualization is achieved through a force-directed layout algorithm to display the relationships between universities, teachers, and other entities.

          <a href="https://observablehq.com/@99124bd25029b379/untitled" target="_blank">Demo of this project at Observable </a>

# articles
  - title: Articles # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: ã€Šå…¨é¢ä¿éšœæ€§æ”¶è´­å¯å†ç”Ÿèƒ½æºç”µé‡ç›‘ç®¡åŠæ³•ã€‹åˆ†æè§£è¯»åŠåº”å¯¹ç­–ç•¥
        additional_links:
          - title: ã€Šå…¨é¢ä¿éšœæ€§æ”¶è´­å¯å†ç”Ÿèƒ½æºç”µé‡ç›‘ç®¡åŠæ³•ã€‹åˆ†æè§£è¯»åŠåº”å¯¹ç­–ç•¥
            icon: fa-brands fa-weixin
            url: https://mp.weixin.qq.com/s/3AuebpoPGnO-2Ck_mrOCgw
        description: |
           æœ¬æ–‡ç« æ—¨åœ¨åˆ†æå›½å®¶å‘æ”¹å§”äº2024å¹´3æœˆ18æ—¥å‘å¸ƒçš„ã€Šå…¨é¢ä¿éšœæ€§æ”¶è´­å¯å†ç”Ÿèƒ½æºç”µé‡ç›‘ç®¡åŠæ³•ã€‹å¯¹æ–°èƒ½æºåœºç«™è¿è¥çš„å½±å“ã€‚é€šè¿‡æ¢³ç†è¯¥æ”¿ç­–çš„è¿‡å¾€ç‰ˆæœ¬ï¼Œå¹¶ç»“åˆå±±è¥¿çœçš„å…·ä½“è§„åˆ™ï¼Œå¯¹æ”¿ç­–å®æ–½å¯¹ç”µåŠ›å¸‚åœºå¯èƒ½å¸¦æ¥çš„å½±å“è¿›è¡Œäº†æ·±å…¥ç ”ç©¶ä¸è¯„ä¼°ã€‚
           
           <a href="https://mp.weixin.qq.com/s/3AuebpoPGnO-2Ck_mrOCgw" target="_blank">Click here to view this article</a>

         
      - layout: right
        title: å±±è¥¿ç”µåŠ›å¸‚åœºè§„åˆ™ä½“ç³»V14å˜åŒ–å’Œè§£è¯»-æ–°èƒ½æºéƒ¨åˆ†
        description: |
           æœ¬æ–‡é‡ç‚¹æ¢³ç†äº†æ–°å‘å¸ƒçš„ã€ŠV14å±±è¥¿ç”µåŠ›ç°è´§å¸‚åœºäº¤æ˜“å®æ–½ç»†åˆ™ã€‹ä¸­ä¸æ–°èƒ½æºç›¸å…³çš„11é¡¹ä¿®æ”¹ã€6é¡¹æ–°å¢åŠ1é¡¹åˆ é™¤å†…å®¹ï¼Œå¹¶åœ¨æ­¤åŸºç¡€ä¸Šè¿›è¡Œäº†ç³»ç»Ÿåˆ†æå’Œæ·±å…¥è§£è¯»ã€‚

           <a href="https://mp.weixin.qq.com/s/zkKmIThE_8NTFaR0Rwo1nw" target="_blank">Click here to view this article</a>

          
      - layout: right
        title: â€œè‡ªè°ƒåº¦â€è¿˜æ˜¯â€œæŠ¥é‡æŠ¥ä»·â€ï¼Ÿå‚¨èƒ½ç°è´§å¸‚åœºç”³æŠ¥ç­–ç•¥
        description: |
           æœ¬æ–‡åœ¨é’ˆå¯¹å®‰å¾½ç”µåŠ›å¸‚åœºç¬¬å››æ¬¡è¯•è¿è¡ŒæœŸé—´æŠ«éœ²çš„å‡ºæ¸…ä»·æ ¼è¿›è¡Œæ•°æ®åˆ†æï¼Œåœ¨æ­¤åŸºç¡€ä¸Šï¼Œè¿›ä¸€æ­¥é’ˆå¯¹ç‹¬ç«‹å‚¨èƒ½ç”µç«™çš„ç”³æŠ¥ç­–ç•¥è¿›è¡Œäº†åˆ†æï¼Œå¾—å‡ºè‡ªè°ƒåº¦æ¨¡å¼ä¸‹æ¨èâ€œåˆå……æ™šæ”¾â€çš„ç­–ç•¥ã€‚

           <a href="https://mp.weixin.qq.com/s/Sw4W66OfG0FSVJc97SUgow" target="_blank">Click here to view this article</a>

         
# hobbies
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data science and algorithm engineering some of my other interests and hobbies are:
      - â›°ï¸ Traveling
      - ğŸ“– Reading
      - ğŸµ Everything about music

      ![Trees](images/landscape-trees.jpg "Trees")

  - title: In the End # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/emmonade
        # link_text: Project Website
        additional_links:
          - title:  emmonade
            icon: fab fa-github
            url: github.com/emmonade
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          to be continued...
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
