# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yue Hong | 洪玥
title: Power Market Algorithm Engineer, Passionate about Data Science
email: 18916838915@163.com
website: https://emmonade.github.io/homepage/
location: Beijing, China

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Yue Hong and you can call me Luna in English, and I'm currently an algorithm engineer. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Statistics</mark>、<mark>Python</mark> and <mark>Eating Delicious Food</mark>

content:
  - title: Porfolio # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
# experience
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
# education
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Peking University
        caption: 2021 - 2013
        sub_title: MSc Applied Statistics
        quote: >
          Established in 1898, Peking University is the oldest higher education institution in China, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in modern China.
        description: | # this will include new lines to allow paragraphs
          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
        
          <a href="lib/thesis_Bsc.pdf" target="_blank">Click here to view my master’s thesis.</a>
          
      - layout: left
        title:  East China Normal University
        caption: 2016 - 2024
        sub_title: BSc Statistics
        quote: >
          ECNU is a public research university located in Shanghai, China. Established in 1951 through the merger of Daxia University and Guanghua University, it is the first normal university founded by the People’s Republic of China.
        description: | # this will include new lines to allow paragraphs
          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
        
          <a href="lib/thesis_Bsc.pdf" target="_blank">Click here to view my undergraduate thesis.</a>
# hobbies
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data science and algorithm engineering some of my other interests and hobbies are:
      - Traveling
      - Reading
      - Everything about music

      Look at this cool image  
      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
